import Foundation
import Quotas
import Mockable

/// Repository protocol for storing provider settings (e.g., isEnabled state).
/// Tests use MockProviderSettingsRepository (generated by @Mockable).
/// App uses UserDefaultsProviderSettingsRepository.
@Mockable
public protocol ProviderSettingsRepository: Sendable {
    /// Gets the enabled state for a provider (defaults to true if not set)
    func isEnabled(forProvider id: String) -> Bool

    /// Sets the enabled state for a provider
    func setEnabled(_ enabled: Bool, forProvider id: String)

    /// Gets the enabled state for a provider with a custom default
    func isEnabled(forProvider id: String, defaultValue: Bool) -> Bool

    /// Gets the custom card URL for a provider (nil if not set)
    func customCardURL(forProvider id: String) -> String?

    /// Sets the custom card URL for a provider (empty string or nil to remove)
    func setCustomCardURL(_ url: String?, forProvider id: String)

    /// The `kind` of the data source a provider uses — what Settings calls
    /// PROBE MODE. `nil` until the person picks one.
    func dataSourceKind(forProvider id: String) -> String?

    /// Saves the data source a provider uses.
    func setDataSourceKind(_ kind: String, forProvider id: String)

    /// A provider's on/off setting by name — `claude.cliFallbackEnabled` is
    /// `isOn("cliFallbackEnabled", forProvider: "claude")`. `nil` when never set.
    func isOn(_ setting: String, forProvider id: String) -> Bool?

    /// Saves a provider's on/off setting by name.
    func setOn(_ on: Bool, _ setting: String, forProvider id: String)

    /// Gets the user's provider display order as provider IDs, empty when the
    /// user never reordered. IDs missing from the list keep their registration
    /// position; IDs of providers that no longer exist are ignored.
    func providerOrder() -> [String]

    /// Persists the user's provider display order.
    /// An empty list clears the stored order.
    func setProviderOrder(_ order: [String])
}

public extension ProviderSettingsRepository {
    /// Default for conformers that keep no choice: the definition's default applies.
    func dataSourceKind(forProvider id: String) -> String? { nil }

    /// Default for conformers that keep no choice.
    func setDataSourceKind(_ kind: String, forProvider id: String) {}

    /// Default for conformers that keep no such setting.
    func isOn(_ setting: String, forProvider id: String) -> Bool? { nil }

    /// Default for conformers that keep no such setting.
    func setOn(_ on: Bool, _ setting: String, forProvider id: String) {}

    /// Default for conformers that keep no order: the registration order applies.
    func providerOrder() -> [String] { [] }

    /// Default for conformers that keep no order: nothing to persist.
    func setProviderOrder(_ order: [String]) {}
}

// MARK: - Default Implementation

public extension ProviderSettingsRepository {
    /// Default implementation that uses `true` as the default value
    func isEnabled(forProvider id: String) -> Bool {
        isEnabled(forProvider: id, defaultValue: true)
    }
}
